project_id = "zeytanlupmvxkraqwosi"

[functions.create-payment-order]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.process-resume]
verify_jwt = true

[functions.generate-feedback]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true